[versions]
plugin_kotlin = "2.2.20"
plugin_moddev = "2.0.134"
plugin_curseForge = "1.+"
plugin_modrinth = "2.+"


minecraft = "1.21.1"
neoforge = "21.1.217"
kotlinForForge = "5.10.0"
parchmentmc = "2024.11.17"

easyNestConfig = "4.0.0"
jei = "19.21.0.247"
mekanism = "1.21.1-10.7.17.83"
mekanismExtras = "7135934" # 1.2.6.1
igleelib = "7000755" # 1.2.7
evolvedMekanism = "7321395" # 1.2.1-fix2
mekanismElements = "6393948" # 1.4
mekasnismMoreMachine = "7324317" # 1.2.1


[libraries]
kotlinForForge = { module = "thedarkcolour:kotlinforforge-neoforge", version.ref = "kotlinForForge" }

easyNestConfig = { module = "dev.lapis256:EasyNestConfig", version.ref = "easyNestConfig" }
jei = { module = "mezz.jei:jei-1.21.1-neoforge", version.ref = "jei" }
mekanism = { module = "mekanism:Mekanism", version.ref = "mekanism" }
mekanismExtras = { module = "curse.maven:mekanism-extras-1026040", version.ref = "mekanismExtras" }
igleelib = { module = "curse.maven:iglee-library-541199", version.ref = "igleelib" }
evolvedMekanism = { module = "curse.maven:evolved-mekanism-1230085", version.ref = "evolvedMekanism" }
mekanismElements = { module = "curse.maven:mekanism-elements-1103224", version.ref = "mekanismElements" }
mekanismMoreMachine = { module = "curse.maven:mekanism-more-machine-1275257", version.ref = "mekasnismMoreMachine" }


[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "plugin_kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "plugin_kotlin" }
moddev = { id = "net.neoforged.moddev", version.ref = "plugin_moddev" }
curseForge = { id = "net.darkhax.curseforgegradle", version.ref = "plugin_curseForge" }
modrinth = { id = "com.modrinth.minotaur", version.ref = "plugin_modrinth" }
